### ISSUE TITLE
 Uncaught Time zone America/Chicago is unknown to source TZDB: 2018

### ISSUE THREAD

**Issue by mstich-mcmservices** [Joshua-Ferguson/time_machine#69]
Built flutter web - I get this error on startup.  Anyone know what might be causing this?

**Comment by rich-j** [comment]
@mstich-mcmservices usually web data issues are due to the data files not being found for release builds - see issue #25

**Comment by mstich-mcmservices** [comment]
Thanks for the response.  I checked out that issue and I believe you are correct.  However, I have scoured the time_machine package and I think I am missing something here.  I have been successfully using this package for android and iOS and now I'm trying to get web to run.  I believe I have cultures.bin and tzdb.bin in correct locations in the source tree.  But I am missing how tzdb.json gets created.

**Comment by mstich-mcmservices** [comment]
Apologies.  I overlooked it in the repo.
